WIFI_SSID = "YOUR_SSID"
WIFI_PASSWORD = "YOUR_PASSWORD"
URL_TIDETIME = "https://environment.data.gov.uk/flood-monitoring/id/measures/YOUR_NEAREST-level-tidal_level-Mean-15_min-mAOD/readings?_sorted&_limit=2"
URL_AURORA = "https://aurora.hendrikpeter.net/api/aurora_data.json"
URL_WEATHER = "https://api.open-meteo.com/v1/forecast?latitude=YOUR_LAT&longitude=YOUR_LONG&hourly=temperature_2m,precipitation_probability,rain,showers,snowfall,weather_code,wind_speed_10m&timezone=Europe%2FLondon&forecast_days=1"